workflows:
  flutter-build:
    name: Flutter Build

    environment:
      flutter: stable

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release