name: dllni_user_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  common_package:
    path: common_package

  easy_localization: ^3.0.8
  flutter_bloc: ^9.1.1
  dio: ^5.9.1
  injectable: ^2.7.1+4
  get_it: ^8.2.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  awesome_notifications: ^0.11.0
  flutter_svg: ^2.0.10
  flutter_animate: ^4.5.2
  image_picker: ^1.2.1
  toastification: ^3.0.3
  font_awesome_flutter: ^11.0.0
  mason: ^0.1.2
  tab_indicator_styler: ^2.0.0
  pusher_channels_flutter: ^2.4.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  dartz: ^0.10.1
  geolocator: ^13.0.2
  flutter_cube_transition: ^1.0.2
  dotted_border: ^3.1.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  speech_to_text: ^7.3.0
  smooth_page_indicator: ^2.0.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  app_links: ^6.4.1
  share_plus: ^11.0.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.7.1
  injectable_generator: ^2.12.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  assets:
    - assets/translations/
    - assets/images/
    - assets/images/svgs/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
