import json, uuid
from pathlib import Path

WORKER = Path(r"..\dllni_cleaning_owner_app\design\worker-app-redesign\worker-app-redesign.pen")
OUT = Path(r"design\customer-app-redesign\customer-app-redesign.pen")
base = json.loads(WORKER.read_text(encoding="utf-8"))
variables = dict(base.get("variables", {}))
variables.update({
    "customer-canvas":{"type":"color","value":"#F7F8FC"},
    "customer-surface":{"type":"color","value":"#FFFFFF"},
    "customer-soft-blue":{"type":"color","value":"#EEF2FF"},
    "customer-soft-mint":{"type":"color","value":"#ECFDF8"},
    "customer-soft-orange":{"type":"color","value":"#FFF7ED"},
})
i=0
def nid():
    global i; i+=1; return f"C{i:06d}"
def text(s,size=14,weight="500",fill="#0F172A",w=None):
    n={"type":"text","id":nid(),"name":"Text","content":s,"fontFamily":"Cairo","fontSize":size,"fontWeight":weight,"fill":fill}
    if w is not None: n.update({"width":w,"textGrowth":"fixed-width","lineHeight":1.45})
    return n
def frame(name,children=None,**kw):
    n={"type":"frame","id":nid(),"name":name}; n.update(kw)
    if children is not None: n["children"]=children
    return n
def icon(name,color="#1E2A7B",size=20):
    return {"type":"icon","id":nid(),"name":name,"icon":name,"library":"lucide","fill":color,"width":size,"height":size}
def chip(label,fg="#1E2A7B",bg="#E9ECF8"):
    return frame("Chip "+label,[text(label,11,"700",fg)],fill=bg,cornerRadius=999,padding=[6,10],alignItems="center")
def button(label,primary=True):
    bg="#1E2A7B" if primary else "#FFFFFF"; fg="#FFFFFF" if primary else "#1E2A7B"
    return frame("Button "+label,[text(label,14,"700",fg)],width="fill_container",height=50,fill=bg,cornerRadius=14,padding=[0,16],justifyContent="center",alignItems="center",stroke=None if primary else "#1E2A7B",strokeWidth=0 if primary else 1)
def row(title,sub="",ico="circle",trail=None):
    kids=[frame("Icon",[icon(ico)],width=40,height=40,fill="#EEF2FF",cornerRadius=12,justifyContent="center",alignItems="center"),
          frame("Copy",[text(title,14,"700","#0F172A","fill_container")]+([text(sub,11,"500","#64748B","fill_container")] if sub else []),width="fill_container",layout="vertical",gap=3)]
    if trail: kids.insert(0,trail)
    return frame("Row "+title,kids,width="fill_container",fill="#FFFFFF",cornerRadius=16,padding=12,gap=10,alignItems="center",stroke="#E2E8F0",strokeWidth=1)
def price(label,val,strong=False):
    return frame("Price "+label,[text(val,13,"800" if strong else "700","#1E2A7B"),text(label,12,"700" if strong else "500","#0F172A")],width="fill_container",justifyContent="space_between",alignItems="center")
def header(title,sub=""):
    kids=[text(title,21,"800","#0F172A","fill_container")]
    if sub:kids.append(text(sub,11,"500","#64748B","fill_container"))
    return frame("Header",kids,width="fill_container",layout="vertical",gap=3,alignItems="end")
def phone(name,title,sub,body,source,owner="existing state",cta=None,route="existing route",rule="Presentation only; preserve current behavior"):
    meta={"type":"developer-screen-handoff","flutterScreen":name,"sourcePath":source,"route":route,
          "stateOwner":owner,"behaviorSource":"dllni-user-app dev branch","visualSource":"customer-app-redesign.pen",
          "implementationRule":rule,"doNotChange":"API contracts, repositories, use cases, pricing, eligibility, lifecycle"}
    kids=[frame("Status",[text("9:41",10,"700","#334155"),frame("Signals",[icon("wifi","#334155",12),icon("battery","#334155",14)],gap=5)],width="fill_container",height=22,justifyContent="space_between",alignItems="center"),
          header(title,sub),frame("Body",body,width="fill_container",layout="vertical",gap=11)]
    if cta:kids.append(button(cta))
    return frame(name,kids,width=390,height=844,fill="#F7F8FC",cornerRadius=30,padding=[12,16,16,16],gap=12,layout="vertical",stroke="#E2E8F0",strokeWidth=1,clip=True,metadata=meta)
def board(index,title,screens=None,extras=None):
    kids=[frame("Board Header",[frame("No",[text(f"{index:02d}",12,"800","#FFFFFF")],width=42,height=42,fill="#1E2A7B",cornerRadius=12,justifyContent="center",alignItems="center"),
        frame("Title",[text(title,28,"800","#0F172A","fill_container"),text("Client review + Flutter developer handoff",11,"600","#64748B","fill_container")],width="fill_container",layout="vertical",gap=3)],width="fill_container",gap=14,alignItems="center")]
    if extras:kids.extend(extras)
    if screens:
        for j in range(0,len(screens),4):
            kids.append(frame("Screens Row",screens[j:j+4],width="fill_container",gap=24,alignItems="start"))
    return frame(f"{index:02d} — {title}",kids,width=1740,fill="#F7F8FC",padding=32,gap=24,layout="vertical",stroke="#E2E8F0",strokeWidth=1)
boards=[]
cover=frame("Hero",[frame("Copy",[text("تطبيق دلّني للمستخدم",36,"800","#FFFFFF","fill_container"),text("إعادة تصميم شاملة: أوضح في الحجز، أبسط في التنقل، وأكثر شفافية في التسعير.",16,"600","#DCE2FF","fill_container")],width="fill_container",layout="vertical",gap=9),frame("Mark",[icon("sparkles","#FFFFFF",36)],width=84,height=84,fill="#FFFFFF18",cornerRadius=22,justifyContent="center",alignItems="center")],width="fill_container",height=180,fill="#1E2A7B",cornerRadius=24,padding=26,gap=20,justifyContent="space_between",alignItems="center")
boards.append(board(0,"Cover + Product Map",extras=[cover,frame("Flows",[row("الدخول والهوية","Login → OTP → Home","shield-check"),row("طلب التنظيف","Service → Rooms → Workers → Schedule → Review","sparkles"),row("متابعة الطلب","Tracking → Verification → Completion","route"),row("الحساب","Profile → Addresses → Coupons","user-round")],width="fill_container",gap=12)]))
boards.append(board(1,"Design System",extras=[frame("Foundations",[row("ألوان المنتج","Indigo + neutral surfaces + semantic states","palette"),row("Typography","Cairo · Arabic-first RTL","type"),row("Spacing","4 / 8 / 12 / 16 / 24 / 32","ruler"),row("Accessibility","44dp targets · 200% text scale","accessibility")],width="fill_container",gap=12)]))
comp=[button("متابعة"),row("العنوان الحالي","المنزل · المزة","map-pin"),chip("قيد التنفيذ","#059669","#ECFDF5"),price("الإجمالي","195,000 ل.س",True)]
for c in comp:c["reusable"]=True;c["metadata"]={"type":"developer-component","implementation":"presentation only","rtl":True,"westernNumerals":True}
boards.append(board(2,"Shared Components",extras=[frame("Library",comp,width="fill_container",gap=14,alignItems="center")]))
auth=[
phone("LoginScreen","تسجيل الدخول","أهلاً بعودتك",[row("رقم الهاتف","اكتب رقم الهاتف المرتبط بالحساب","phone"),row("كلمة المرور","إظهار / إخفاء","lock-keyhole"),text("نسيت كلمة المرور؟",12,"700","#1E2A7B")],"lib/features/auth/view/screens/login_screen.dart","Auth state","تسجيل الدخول"),
phone("RegisterScreen","إنشاء حساب","بيانات أساسية فقط",[row("الاسم الكامل","","user"),row("رقم الهاتف","","phone"),row("كلمة المرور","","lock-keyhole"),chip("الموافقة على الشروط")],"lib/features/auth/view/screens/register_screen.dart","Auth state","إنشاء الحساب"),
phone("VerifyAccountScreen","رمز التحقق","أرسلنا رمزاً إلى رقمك",[frame("OTP",[frame("Cell",[text("4",20,"800","#0F172A")],width=48,height=56,fill="#FFFFFF",cornerRadius=13,stroke="#1E2A7B",strokeWidth=1,justifyContent="center",alignItems="center") for _ in range(5)],width="fill_container",gap=10,justifyContent="center"),text("إعادة الإرسال خلال 00:42",12,"600","#64748B")],"lib/features/auth/view/screens/verify_account_screen.dart","Auth state","تحقق"),
phone("LoginHelpScreen","مساعدة تسجيل الدخول","حلول سريعة",[row("لم يصلني رمز التحقق","","message-circle"),row("غيّرت رقم الهاتف","","phone-forwarded"),row("استعادة الحساب","","circle-help")],"lib/features/auth/view/screens/login_help_screen.dart","Auth state")]
boards.append(board(3,"Authentication",auth))
home=[phone("HomeScreen","الرئيسية","شو حابب تعمل اليوم؟",[row("تنظيف","حجز منزل أو مناسبة","sparkles"),row("مطاعم","اطلب وجبتك","utensils"),row("سوبرماركت","احتياجاتك اليومية","shopping-basket"),frame("Active Order",[chip("قيد التنفيذ","#059669","#ECFDF5"),text("عامل التنظيف في الطريق",15,"800","#0F172A"),text("الوصول المتوقع 10:30 ص",11,"600","#64748B"),button("متابعة الطلب",False)],width="fill_container",fill="#FFFFFF",cornerRadius=18,padding=14,gap=8,layout="vertical",stroke="#E2E8F0",strokeWidth=1)],"lib/features/home/view/screens/home_screen.dart","Home state"),
phone("MainScreen","دلّني","تنقل عالمي",[row("الرئيسية","","home"),row("اكتشف","","compass"),row("طلباتي","","receipt-text"),row("حسابي","","user-round")],"lib/features/main/view/screens/main_screen.dart","Main navigation")]
boards.append(board(4,"Main Home + Navigation",home))
profile=[phone("ProfileScreen","حسابي","بياناتك وإعداداتك",[row("التفاصيل الشخصية","الاسم ورقم الهاتف","user-round"),row("عناويني","العناوين المحفوظة","map-pin"),row("الكوبونات","المتاح للاستخدام","ticket-percent"),row("الإشعارات","","bell"),row("الشروط والأحكام","","file-text")],"lib/features/profile/view/screens/profile_screen.dart","Profile state"),
phone("PersonalDetailsScreen","تفاصيل الحساب","بياناتك الشخصية",[row("الاسم الكامل","مصطفى فارس","user"),row("رقم الهاتف","09xx xxx xxx","phone"),row("حالة الحساب","موثق","badge-check")],"lib/features/profile/view/screens/personal_details_screen.dart","Profile state","حفظ التغييرات")]
boards.append(board(5,"Profile + Settings",profile))
addresses=[phone("MyAddressesScreen","عناويني","اختر العنوان الافتراضي",[row("المنزل","المزة · شارع ...","house",chip("افتراضي")),row("العمل","المالكي · شارع ...","building-2"),button("إضافة عنوان جديد",False)],"lib/features/profile/view/screens/my_addresses_screen.dart","Address state"),
phone("AddAddressScreen","إضافة عنوان","حدد الموقع ثم التفاصيل",[frame("Map",[icon("map-pin","#1E2A7B",30),text("حدد النقطة على الخريطة",13,"700","#334155")],width="fill_container",height=220,fill="#EEF2FF",cornerRadius=18,gap=8,layout="vertical",justifyContent="center",alignItems="center"),row("اسم العنوان","مثال: المنزل","tag"),row("تفاصيل إضافية","البناء / الطابق / ملاحظات","map")],"lib/features/profile/view/screens/add_address_screen.dart","Address state","حفظ العنوان")]
boards.append(board(6,"Addresses + Location",addresses))
boards.append(board(7,"Notifications + Coupons",[phone("NotificationsScreen","الإشعارات","آخر التحديثات",[row("تم تأكيد طلب التنظيف","اليوم · 10:15 ص","check-circle-2"),row("العامل في الطريق","الوصول المتوقع قريباً","route"),row("كوبون جديد متاح","","ticket-percent")],"lib/features/profile/view/screens/notifications_screen.dart","Notification state"),phone("CouponsScreen","الكوبونات","المتاح قبل انتهاء الصلاحية",[frame("Coupon",[text("CLEAN20",16,"800","#1E2A7B"),text("خصم 20% على خدمة التنظيف",13,"700","#0F172A"),text("صالح حتى 30/09/2026",10,"600","#64748B"),button("استخدام الكوبون",False)],width="fill_container",fill="#FFFFFF",cornerRadius=18,padding=14,gap=8,layout="vertical",stroke="#E2E8F0",strokeWidth=1)],"lib/features/profile/view/screens/coupons_screen.dart","Coupon state")]))
discover=[phone("ClMainScreen","التنظيف","اختر نوع الخدمة",[row("تنظيف منزل","غرف، أحجام، عمال وموعد","house"),row("تنظيف مكتب","المساحة والخدمة","building-2"),row("تنظيف مناسبات","عدة أيام أو جلسات","party-popper"),row("خدمات خاصة","إضافات حسب الحاجة","wand-sparkles")],"lib/features/cl_main/view/screens/cl_main_screen.dart","ClMainBloc"),
phone("ClMainHomeDescriptionScreen","تنظيف المنزل","صف المكان بدقة",[row("نوع العقار","شقة","house"),row("الغرف والأحجام","7 وحدات مختارة","bed-double"),row("التقدير","يتحدث مع كل تعديل","badge-dollar-sign")],"lib/features/cl_main/view/screens/cl_main_home_description_screen.dart","ClMainBloc","اختيار الغرف"),
phone("ClMainOccasionDescriptionScreen","تنظيف مناسبة","نوع المناسبة ومتطلباتها",[row("نوع المناسبة","زفاف / حفلة / اجتماع","party-popper"),row("عدد الحضور","عند الحاجة","users"),row("الخدمات الخاصة","من إعدادات السيرفر","sparkles")],"lib/features/cl_main/view/screens/cl_main_occasion_description_screen.dart","ClMainBloc","متابعة")]
boards.append(board(8,"Cleaning Discovery",discover))
def roomblock(name,ico):
    sizes=[]
    for sz in ["صغير","متوسط","كبير"]:
        sizes.append(frame(sz,[text(sz,11,"700","#0F172A"),text("سعر الوحدة",9,"500","#64748B"),text("— ل.س",11,"800","#1E2A7B"),frame("Qty",[icon("minus","#64748B",12),text("0",11,"800","#0F172A"),icon("plus","#1E2A7B",12)],gap=7,alignItems="center"),text("المجموع: — ل.س",9,"600","#64748B")],width="fill_container",fill="#F7F8FC",cornerRadius=12,padding=8,gap=3,layout="vertical",alignItems="center"))
    return frame("Room "+name,[frame("Room title",[icon(ico),text(name,14,"800","#0F172A")],gap=7,alignItems="center"),frame("Sizes",sizes,width="fill_container",gap=7)],width="fill_container",fill="#FFFFFF",cornerRadius=16,padding=12,gap=10,layout="vertical",stroke="#E2E8F0",strokeWidth=1)
room_note=frame("Pricing Note",[icon("info","#0284C7",16),text("يظهر سعر كل حجم فور توفر التقدير. قبل ذلك يبقى السعر فارغاً بدلاً من عرض رقم غير مؤكد.",10,"600","#475569","fill_container")],width="fill_container",fill="#F0F9FF",cornerRadius=12,padding=10,gap=7,alignItems="center")
room_a=phone("RoomPricingSelectorA","الغرف والأحجام","اختر الحجم ثم الكمية وشاهد السعر مباشرة",[roomblock("غرفة نوم","bed-double"),roomblock("حمام","bath"),price("إجمالي الغرف المختارة","— ل.س",True),room_note],"lib/features/cl_main/view/screens/cl_main_home_description_screen.dart","ClMainBloc + estimate","متابعة الغرف",rule="Room type/size/quantity come from CleaningRoomSizeBreakdown; unit/subtotal only from estimate/config")
room_b=phone("RoomPricingSelectorB","الغرف والأحجام","تكملة نفس قائمة الغرف",[roomblock("مطبخ","cooking-pot"),roomblock("غرفة معيشة","sofa"),price("إجمالي الغرف المختارة","— ل.س",True)],"lib/features/cl_main/view/screens/cl_main_home_description_screen.dart","ClMainBloc + estimate","متابعة الغرف",rule="Same scrollable room selector; preserve estimate refresh behavior")
room_c=phone("RoomPricingSelectorC","الغرف والأحجام","باقي أنواع الغرف المتاحة",[roomblock("شرفة","sun"),roomblock("ممر","move-horizontal"),row("مستودع","صغير / متوسط / كبير مع سعر وكمية","warehouse"),price("إجمالي الغرف المختارة","— ل.س",True)],"lib/features/cl_main/view/screens/cl_main_home_description_screen.dart","ClMainBloc + estimate","متابعة إلى العمال",rule="Same room selector; shed also supports small/medium/large using the same component")
booking=[phone("BookingContext","تفاصيل الخدمة","الخطوة 1 من 6",[row("نوع العقار","شقة","house"),row("نوع التنظيف","تنظيف شامل","sparkles"),row("الخدمات الأساسية","3 خدمات","list-checks")],"lib/features/cl_main/view/screens/cl_main_home_description_screen.dart","ClMainBloc","اختيار الغرف"),room_a,room_b,room_c,
phone("WorkerSelection","اختيار العمال","الخطوة 3 من 6",[row("التوزيع التلقائي","دلّني يختار الفريق المناسب","wand-sparkles",chip("موصى به","#059669","#ECFDF5")),row("عامل سابق","من تعاملت معهم","history"),row("عامل محدد","عند توفره","user-check"),row("تفضيل الجنس","حسب السياسة والتوفر","users")],"lib/features/cl_main/view/screens/cl_main_service_schedule_screen.dart","ClMainBloc","متابعة"),
phone("CleaningExtras","الإضافات","الخطوة 4 من 6",[row("مواد التنظيف","عند الحاجة","spray-can"),row("خدمات خاصة","من إعدادات السيرفر","wand-sparkles"),row("Open Time","عند دعمه","timer-reset")],"lib/features/cl_main/view/screens/cl_main_service_schedule_screen.dart","ClMainBloc","اختيار الموعد"),
phone("ScheduleAndAddress","الموعد والعنوان","الخطوة 5 من 6",[row("التاريخ","30/09/2026","calendar-days"),row("الوقت","09:00 ص","clock-3"),row("العنوان","المنزل · المزة","map-pin"),row("حجز متكرر","اختياري","repeat-2")],"lib/features/cl_main/view/screens/cl_main_service_schedule_screen.dart","ClMainBloc","مراجعة الطلب")]
boards.append(board(9,"Cleaning Booking Builder",booking))
reviewbody=[frame("Service",[text("تنظيف منزل",16,"800","#0F172A"),text("شقة · 7 وحدات · 2 عامل",11,"600","#64748B"),text("30/09/2026 · 09:00 ص",11,"600","#64748B")],width="fill_container",fill="#FFFFFF",cornerRadius=18,padding=14,gap=5,layout="vertical",stroke="#E2E8F0",strokeWidth=1),frame("Rooms",[text("تفصيل الغرف",14,"800","#0F172A"),price("غرفة نوم · متوسط × 2","— × 2 = — ل.س"),price("حمام · صغير × 2","— × 2 = — ل.س"),price("مطبخ · متوسط × 1","— × 1 = — ل.س"),text("تعديل الغرف",11,"700","#1E2A7B")],width="fill_container",fill="#FFFFFF",cornerRadius=18,padding=14,gap=9,layout="vertical",stroke="#E2E8F0",strokeWidth=1),frame("Summary",[price("قيمة الخدمة","180,000 ل.س"),price("بدل المواصلات","20,000 ل.س"),price("الإضافات","15,000 ل.س"),price("الخصم","-20,000 ل.س"),price("الإجمالي","195,000 ل.س",True)],width="fill_container",fill="#FFFFFF",cornerRadius=18,padding=14,gap=9,layout="vertical",stroke="#E2E8F0",strokeWidth=1)]
boards.append(board(10,"Cleaning Review + Confirmation",[phone("BookingReview","مراجعة الطلب","كل التفاصيل قبل التأكيد",reviewbody,"lib/features/cl_main/view/screens/cl_main_service_schedule_screen.dart","ClMainBloc + estimate","تأكيد الطلب",rule="Show only customer-facing price fields from estimate response"),phone("BookingSuccess","تم تأكيد طلبك","يمكنك متابعة الحالة الآن",[frame("Success",[icon("circle-check-big","#059669",42),text("طلبك وصلنا بنجاح",18,"800","#0F172A"),text("سنبدأ تجهيز الفريق المناسب.",11,"600","#64748B")],width="fill_container",height=220,fill="#ECFDF5",cornerRadius=22,gap=9,layout="vertical",justifyContent="center",alignItems="center"),row("رقم الطلب","#CL-20481","receipt-text"),row("الحالة","جاري البحث عن الفريق","users-round")],"lib/features/cl_main/view/screens/cl_main_service_schedule_screen.dart","ClMainBloc","متابعة الطلب")]))
orders=[phone("OrdersScreen","طلباتي","كل الخدمات في مكان واحد",[row("تنظيف منزل","قيد التنفيذ · اليوم 09:00","sparkles",chip("قيد التنفيذ","#059669","#ECFDF5")),row("مطعم","تم التسليم · أمس","utensils",chip("مكتمل","#64748B","#F1F5F9")),row("سوبرماركت","قيد التجهيز","shopping-basket",chip("قيد التجهيز","#0284C7","#F0F9FF"))],"lib/features/orders/view/screens/orders_screen.dart","Orders state")]
boards.append(board(11,"Cleaning Orders List",orders))
def lifecycle(name,state,detail,cta,ico):
    return phone(name,"تفاصيل طلب التنظيف","الحالة والإجراء التالي",[frame("State",[icon(ico,"#1E2A7B",28),chip(state),text(detail,13,"700","#0F172A","fill_container")],width="fill_container",fill="#FFFFFF",cornerRadius=18,padding=14,gap=9,layout="vertical",stroke="#E2E8F0",strokeWidth=1),row("الموعد","30/09/2026 · 09:00 ص","calendar-days"),row("العنوان","المنزل · المزة","map-pin"),frame("Timeline",[text("إنشاء الطلب ✓",11,"700","#059669"),text("الحالة الحالية ●",11,"800","#1E2A7B"),text("الخطوة التالية",11,"500","#64748B")],width="fill_container",fill="#FFFFFF",cornerRadius=16,padding=12,gap=7,layout="vertical",stroke="#E2E8F0",strokeWidth=1)],"lib/features/orders/view/screens/cleaning_order_details_screen.dart","Cleaning lifecycle state",cta)
life=[lifecycle("TeamSearch","جاري تجهيز الفريق","نبحث عن العمال المناسبين.","إدارة الطلب","users-round"),lifecycle("Traveling","في الطريق","تابع موقع العامل ووقت الوصول.","فتح التتبع","route"),lifecycle("Verification","رمز الأمان","شارك الرمز بعد وصول العامل فقط.","عرض الرمز","shield-check"),lifecycle("InProgress","قيد التنفيذ","الخدمة بدأت ويمكنك متابعة الجلسة.","تفاصيل الجلسة","sparkles"),lifecycle("Extension","قرار مطلوب","العامل طلب وقتاً إضافياً.","مراجعة التمديد","timer-reset"),lifecycle("AwaitingCompletion","بانتظار تأكيدك","راجع الخدمة قبل الإغلاق.","مراجعة الإنجاز","badge-check"),lifecycle("Completed","مكتمل","شكراً لاستخدامك دلّني.","تقييم العامل","star"),lifecycle("Cancelled","ملغي","هذا الطلب لم يعد نشطاً.","عرض التفاصيل","circle-x")]
boards.append(board(12,"Cleaning Order Details / Lifecycle",life))
support=[phone("CleaningOrderRescheduleScreen","تغيير الموعد","ضمن القيود الحالية",[row("الموعد الحالي","30/09/2026 · 09:00 ص","calendar-clock"),row("الموعد الجديد","اختر التاريخ والوقت","calendar-plus")],"lib/features/orders/view/screens/cleaning_order_reschedule_screen.dart","Order reschedule state","حفظ الموعد الجديد"),phone("CleaningOrderProblemReportScreen","الإبلاغ عن مشكلة","اشرح المشكلة بوضوح",[row("الخدمة غير مكتملة","","triangle-alert"),row("مشكلة في الجودة","","badge-alert"),row("أخرى","أضف وصفاً","message-square-text")],"lib/features/orders/view/screens/cleaning_order_problem_report_screen.dart","Issue state","إرسال البلاغ"),phone("CleaningOrderSosScreen","حالة طارئة","استخدمها عند الحاجة فقط",[frame("SOS",[icon("siren","#D92341",36),text("طلب مساعدة عاجلة",17,"800","#D92341"),text("سيتم إرسال بيانات الحجز الحالية.",11,"600","#64748B")],width="fill_container",height=220,fill="#FFF1F2",cornerRadius=22,gap=9,layout="vertical",justifyContent="center",alignItems="center")],"lib/features/orders/view/screens/cleaning_order_sos_screen.dart","SOS state","إرسال SOS"),phone("CleaningWorkerRatingScreen","قيّم تجربتك","ساعدنا في تحسين الخدمة",[frame("Stars",[icon("star","#D97706",26) for _ in range(5)],width="fill_container",gap=8,justifyContent="center"),row("تعليقك","اختياري","message-square")],"lib/features/orders/view/screens/cleaning_worker_rating_screen.dart","Rating state","إرسال التقييم")]
boards.append(board(13,"Cleaning Recovery / Support / Rating",support))
multi=[phone("OccasionSchedule","جدول المناسبة","كل جلسة واضحة",[row("الجلسة 1","30/09/2026 · 4 ساعات","calendar-days"),row("الجلسة 2","01/10/2026 · 5 ساعات","calendar-days"),row("الجلسة 3","02/10/2026 · 3 ساعات","calendar-days")],"lib/features/cl_main/view/screens/cl_main_occasion_schedule_screen.dart","ClMainBloc","متابعة"),phone("RecurringBuilder","تنظيف متكرر","جدول الزيارات",[row("النمط","أسبوعي","repeat-2"),row("عدد الزيارات","4","calendar-range"),row("العامل","نفس العامل عند التوفر","user-check")],"lib/features/cl_main/view/screens/cl_main_service_schedule_screen.dart","ClMainBloc","مراجعة الجدول"),phone("OpenTimeBuilder","وقت مفتوح","مدة مرنة وفق قواعد السيرفر",[row("عدد العمال","2","users"),row("الحد المتوقع","90 دقيقة","timer")],"lib/features/cl_main/view/screens/cl_main_service_schedule_screen.dart","ClMainBloc","متابعة"),phone("MultiDayCleaningDetails","تفاصيل المناسبة","حالة كل جلسة",[row("الجلسة 1","مكتملة","circle-check"),row("الجلسة 2","قيد التنفيذ","loader-circle"),row("الجلسة 3","قادمة","calendar-clock")],"lib/features/orders/view/screens/multi_day_cleaning_order_details_screen.dart","Multi-day state")]
boards.append(board(14,"Multi-day + Recurring + Open-Time",multi))
commerce=[phone("RestaurantOrderSurface","طلب مطعم","نفس لغة الحالة والإجراء",[row("مطعم الشام","3 أصناف · 145,000 ل.س","utensils"),chip("قيد التحضير","#0284C7","#F0F9FF"),button("تتبع الطلب",False)],"lib/features/orders/view/screens/restaurant_order_tracking_screen.dart","Restaurant state"),phone("SupermarketOrderSurface","طلب سوبرماركت","ملخص سريع",[row("السوبرماركت","12 منتج","shopping-basket"),chip("قيد التجهيز","#0284C7","#F0F9FF"),price("الإجمالي","220,000 ل.س",True)],"lib/features/sm_orders/view/screens/sm_order_details_screen.dart","Supermarket state"),phone("DeliveryTrackingSurface","تتبع التوصيل","حالة السائق والمسار",[frame("Map",[icon("map","#1E2A7B",32),text("خريطة التتبع",13,"700","#334155")],width="fill_container",height=230,fill="#EEF2FF",cornerRadius=18,gap=8,layout="vertical",justifyContent="center",alignItems="center"),row("السائق في الطريق","الوصول المتوقع 12 دقيقة","bike")],"lib/features/delivery/presentation/screens/delivery_order_tracking_screen.dart","Delivery state")]
boards.append(board(15,"Commerce Compatibility",commerce))
states=[phone("LoadingState","جارٍ التحميل","حالة عامة",[frame("Skeleton",[frame("S1",width="fill_container",height=90,fill="#F1F5F9",cornerRadius=16),frame("S2",width="fill_container",height=140,fill="#F1F5F9",cornerRadius=16)],width="fill_container",gap=12,layout="vertical")],"shared","shared"),phone("EmptyState","لا توجد بيانات","الخطوة التالية واضحة",[frame("Empty",[icon("inbox","#64748B",36),text("لا توجد طلبات حالياً",15,"800","#0F172A"),text("عندما تنشئ طلباً سيظهر هنا.",11,"600","#64748B")],width="fill_container",height=220,fill="#FFFFFF",cornerRadius=18,gap=9,layout="vertical",justifyContent="center",alignItems="center")],"shared","shared","إنشاء طلب"),phone("ErrorState","تعذر التحميل","إعادة محاولة واضحة",[frame("Error",[icon("wifi-off","#D92341",34),text("تحقق من الاتصال وحاول مرة أخرى.",12,"600","#64748B")],width="fill_container",height=180,fill="#FFF1F2",cornerRadius=18,gap=8,layout="vertical",justifyContent="center",alignItems="center")],"shared","shared","إعادة المحاولة")]
boards.append(board(16,"Loading / Empty / Error / Disabled / Success",states))
mapping=[("Auth","lib/features/auth/view/screens/","Auth state"),("Home","lib/features/home/view/screens/home_screen.dart","Home state"),("Profile","lib/features/profile/view/screens/","Profile state"),("Cleaning","lib/features/cl_main/view/screens/","ClMainBloc"),("Orders","lib/features/orders/view/screens/","Orders + lifecycle state")]
maprows=[row(a,b,"code") for a,b,_ in mapping]
boards.append(board(17,"Developer Handoff / Screen Map",extras=[frame("Contract",[text("Visual source: customer-app-redesign.pen",14,"800","#0F172A"),text("Behavior source: current Flutter dev branch",13,"700","#1E2A7B"),text("لا تغيّر API أو التسعير أو الأهلية أو lifecycle أثناء التنفيذ.",13,"700","#D92341"),text("Arabic RTL · Western 0–9 · Directional APIs · 44dp targets",12,"600","#64748B")],width="fill_container",fill="#FFFFFF",cornerRadius=18,padding=18,gap=8,layout="vertical",stroke="#E2E8F0",strokeWidth=1),frame("Map",maprows,width="fill_container",gap=8,layout="vertical")]))
x=y=0
for idx,b in enumerate(boards):
    b["x"]=x; b["y"]=y; x+=1840
    if (idx+1)%3==0: x=0; y+=2100
root={"version":base.get("version","2.18"),"children":boards,"themes":{"Appearance":["Light"],"Device":["Compact 360","Standard 390","Large 430"]},"variables":variables,"fileToken":str(uuid.uuid4())}
OUT.parent.mkdir(parents=True,exist_ok=True)
OUT.write_text(json.dumps(root,ensure_ascii=False,indent=2),encoding="utf-8",newline="\n")
print("WROTE",OUT,"boards",len(boards),"nodes",i,"bytes",OUT.stat().st_size)
for b in boards: print(b["id"],b["name"])
